Refactor pre-install script for improved clarity
Refactor pre-install script to improve structure and readability. Added language support and updated installation logic.

diff --git a/snap/local/src/pre-install b/snap/local/src/pre-install
--- a/snap/local/src/pre-install
+++ b/snap/local/src/pre-install
@@ -1,122 +1,117 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# acrordrdc env
-progHome="$WINEPREFIX/drive_c/Program Files (x86)/Adobe/Acrobat Reader DC/Reader"
-progBin="AcroRd32.exe"
-progSetup="$WINEPREFIX/drive_c/Program Files (x86)/Adobe/Acrobat Reader DC/Setup Files/{AC76BA86-7AD7-1033-7B44-AC0F074E4100}"
-prefixFont="$WINEPREFIX/drive_c/windows/Fonts"
+# shellcheck disable=SC2164
 
-# Get mspatcha.dll from snap bundle
-cp "$SNAP/sommelier/hooks/mspatcha.dll" "$WINEPREFIX/drive_c/windows/syswow64/mspatcha.dll"
+# Constants
+declare -A LANG_CODES=(
+    ['Czech']='cs_CZ'
+    ['Danish']='da_DK'
+    ['German']='de_DE'
+    ['English']='en_US'
+    ['Spanish']='es_ES'
+    ['Finnish']='fi_FI'
+    ['Croatian']='hr_HR'
+    ['Hungarian']='hu_HU'
+    ['Korean']='ko_KR'
+    ['Dutch']='nl_NL'
+    ['Norwegian Bokmål']='nb_NO'
+    ['Polish']='pl_PL'
+    ['Romanian']='ro_RO'
+    ['Slovak']='sk_SK'
+    ['Slovene']='sl_SI'
+    ['Swedish']='sv_SE'
+    ['Turkish']='tr_TR'
+    ['Ukrainian']='uk_UA'
+    ['Chinese']='zh_CN'
+    ['French']='fr_FR'
+    ['Italian']='it_IT'
+    ['Japanese']='ja_JP'
+    ['Portuguese']='pt_BR'
+    ['Russian']='ru_RU'
+)
+readonly LANG_CODES
 
-INSTALL_URL_DE="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2001320074/AcroRdrDC2001320074_de_DE.exe"
-INSTALL_URL_US="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2001320074/AcroRdrDC2001320074_en_US.exe"
-INSTALL_URL_ES="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2001320074/AcroRdrDC2001320074_es_ES.exe"
-INSTALL_URL_FR="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2001320074/AcroRdrDC2001320074_fr_FR.exe"
-INSTALL_URL_JP="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/2001320074/AcroRdrDC2001320074_ja_JP.exe"
+readonly VERSION=
 
-if [[ ! -f "$prefixFont/Segoe UI.ttf" ]]; then
-  mkdir -p "$prefixFont"
-  ( cd "$prefixFont"
-  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.ttf" -O "Segoe UI.ttf"
-  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.ttf" -O "Segoe UI Semibold.ttf"
-  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/bold/latest.ttf" -O "Segoe UI Bold.ttf"
-  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.ttf" -O "Segoe UI Semibold.ttf"
-  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/light/latest.ttf" -O "Segoe UI Light.ttf"
-  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semilight/latest.ttf" -O "Segoe UI Semilight.ttf"
-  wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/italic/latest.ttf" -O "Segoe UI Italic.ttf" )
-fi
+readonly PREFIX_FONT="${WINEPREFIX}/drive_c/windows/Fonts"
 
-function install() {
-    # Downloads a file with progress using wget and yad
-    wget "${INSTALL_URL}" -O "${TMPDIR}/${INSTALL_EXE}" 2>&1 | \
+readonly RED='\033[0;31m'
+readonly NC='\033[0m' # No Color
+
+function err() {
+  echo -e "${RED}[$(date +'%Y-%m-%dT%H:%M:%S%z')]: $*${NC}" >&2
+}
+
+function install_fonts() {
+  if [[ ! -f "${PREFIX_FONT}/Segoe UI.ttf" ]]; then
+    mkdir -vp "${PREFIX_FONT}"
+    cd "${PREFIX_FONT}"
+    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/normal/latest.ttf" -O "Segoe UI.ttf"
+    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.ttf" -O "Segoe UI Semibold.ttf"
+    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/bold/latest.ttf" -O "Segoe UI Bold.ttf"
+    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semibold/latest.ttf" -O "Segoe UI Semibold.ttf"
+    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/light/latest.ttf" -O "Segoe UI Light.ttf"
+    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/semilight/latest.ttf" -O "Segoe UI Semilight.ttf"
+    wget --no-check-certificate -q "c.s-microsoft.com/static/fonts/segoe-ui/west-european/italic/latest.ttf" -O "Segoe UI Italic.ttf"
+  fi
+}
+
+function is_command_installed() {
+  if ! command -v "${1}" &>/dev/null
+  then
+    err "${1} could not be found"
+    exit 1
+  fi
+}
+
+function main() {
+  is_command_installed '7z'
+  
+  if [[ -z "${VERSION}" ]]; then
+    err "A version is required!"
+    exit 2
+  fi
+
+  choice=$(yad --width 400 --entry --title 'Adobe Acrobat Reader DC' \
+    --center \
+    --width=400 \
+    --button="Install:0" --button="Exit:1" \
+    --text 'Select your language for installer download:' \
+    --entry-text \
+    "${!LANG_CODES[@]}" 2>/dev/null)
+  if [[ -z "${choice}" ]]; then
+    exit 0
+  fi
+
+  install_fonts
+
+  local install_url
+  install_url="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/${VERSION}/AcroRdrDC${VERSION}_${LANG_CODES["${choice}"]}.exe"
+  wget -q --method HEAD "${install_url}" &>/dev/null || install_url="https://ardownload2.adobe.com/pub/adobe/reader/win/AcrobatDC/${VERSION}/AcroRdrDC${VERSION}_${LANG_CODES['English']}.exe" # fallback
+
+  local install_exe
+  install_exe=$(basename "${install_url}")
+  
+  # Downloads a file with progress using wget and yad
+  wget "${install_url}" -O "${TMPDIR}/${install_exe}" 2>&1 | \
     perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
-    yad --progress --title="${INSTALL_EXE}" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape 2>/dev/null
-    # Unpack setup files
-    7z -y x "${TMPDIR}/${INSTALL_EXE}" -o"${TMPDIR}/dl"
-    # Installs the application
-    wine "${TMPDIR}/dl/setup.exe" /sAll
-    # Apply reg
-    wget --no-check-certificate -q https://gist.github.com/mmtrt/896cf131e3956b23e8e47a5a52f58b01/raw/097cbd0eeb836d69a84423aaef9a7ead2840a111/acrordr -P ${TMPDIR} && wine regedit ${TMPDIR}/acrordr && rm ${TMPDIR}/acrordr
-    # set prefix os to xp
-    winetricks --unattended winxp
-    # Rename some files which are going rouge on closing acrordr
-    cd "$WINEPREFIX/drive_c/Program Files (x86)/Common Files/Adobe/ARM/1.0"
-    mv armsvc.exe armsvc.exe_disabled
-    mv AdobeARM.exe AdobeARM.exe_disabled
-    mv AdobeARMHelper.exe AdobeARMHelper.exe_disabled
-    cd "$progHome/AcroCEF"
-    mv RdrServicesUpdater.exe RdrServicesUpdater.exe_disabled
-    mv RdrCEF.exe RdrCEF.exe_disabled
-    # Remove the cached installers & files
-    rm -v "${TMPDIR}/${INSTALL_EXE}" 2>/dev/null
-    rm -rf "${TMPDIR}/dl" 2>/dev/null
-    rm -rf "${TMPDIR}/winetricks" 2>/dev/null
+    yad --progress \
+        --title="Downloading ${install_exe}" \
+        --width=400 \
+        --center \
+        --no-buttons \
+        --auto-close \
+        --auto-kill \
+        --on-top \
+        --no-escape 2>/dev/null
+
+  # Unpack setup files
+  7z -y x "${TMPDIR}/${install_exe}" -o"${TMPDIR}/dl"
+  rm -v "${TMPDIR}/${install_exe}" 2>/dev/null
+  
+  # TODO(miticollo): Improve setup.ini
+  
+  export INSTALL_EXE="${TMPDIR}/dl/setup.exe"
 }
 
-function install_de() {
-    # Modify or remove this as required by your application.
-  if [ -n "${INSTALL_URL_DE}" ]; then
-    INSTALL_URL="${INSTALL_URL_DE}"
-    INSTALL_EXE=$(basename "${INSTALL_URL}")
-    install
-  fi
-}
-
-function install_es() {
-    # Modify or remove this as required by your application.
-  if [ -n "${INSTALL_URL_ES}" ]; then
-    INSTALL_URL="${INSTALL_URL_ES}"
-    INSTALL_EXE=$(basename "${INSTALL_URL}")
-    install
-  fi
-}
-
-function install_fr() {
-    # Modify or remove this as required by your application.
-  if [ -n "${INSTALL_URL_FR}" ]; then
-    INSTALL_URL="${INSTALL_URL_FR}"
-    INSTALL_EXE=$(basename "${INSTALL_URL}")
-    install
-  fi
-}
-
-function install_jp() {
-    # Modify or remove this as required by your application.
-  if [ -n "${INSTALL_URL_JP}" ]; then
-    INSTALL_URL="${INSTALL_URL_JP}"
-    INSTALL_EXE=$(basename "${INSTALL_URL}")
-    install
-  fi
-}
-
-function install_us() {
-    # Modify or remove this as required by your application.
-  if [ -n "${INSTALL_URL_US}" ]; then
-    INSTALL_URL="${INSTALL_URL_US}"
-    INSTALL_EXE=$(basename "${INSTALL_URL}")
-    install
-  fi
-}
-
-  action=$(yad --width 400 --entry --title "Adobe Acrobat Reader DC" \
-      --center \
-      --width=400 \
-      --button="Install:0" --button="Exit:1" \
-      --text "Select your language for installer download:" \
-      --entry-text \
-      "English" "French" "German" "Japanese" "Spanish" 2>/dev/null)
-  ret=$?
-
-  [[ $ret -eq 1 ]] && exit 0
-
-  case $action in
-      Ger*) cmd=$(install_de) ;;
-      Spa*) cmd=$(install_es) ;;
-      Fre*) cmd=$(install_fr) ;;
-      Jap*) cmd=$(install_jp) ;;
-      Eng*) cmd=$(install_us) ;;
-      *) exit 1 ;;
-  esac
-
-  eval $cmd 2>/dev/null
+main
